feat: added the solution to the problem 'A Sereja and Dima'
rychcicki/code-challanges pull request #15
Opened 2023-01-29 22:28 UTC by rychcicki

Solution to the problem 381/A Sereja and Dima.
I am third of execution time, but one of the last of solution size:
https://codeforces.com/problemset/status/381/problem/A/page/1?order=BY_CONSUMED_TIME_ASC

2023-01-30 09:34 UTC, Y0ucandev requested changes

2023-01-30 09:34 UTC, Y0ucandev commented on tasks/src/main/java/org/example/aSerejaAndDima/ASerejaAndDima.java
> +public class ASerejaAndDima {
Możesz link wrzucić dla porządku

2023-01-30 09:34 UTC, Y0ucandev commented on tasks/src/main/java/org/example/aSerejaAndDima/ASerejaAndDima.java
> +    void whoseIsThisCard(short whoseTurnNow, short greaterNumber) {
Zrób z tego metodę która zwraca ta liczbę nie bd trzeba wtedy elsa

2023-01-30 21:16 UTC, rychcicki commented on tasks/src/main/java/org/example/aSerejaAndDima/ASerejaAndDima.java
> +    void whoseIsThisCard(short whoseTurnNow, short greaterNumber) {
Nie do końca wiem, o co chodzi... Ta metoda dodaje liczbę na karcie do sumy liczb Sereji lub Dimy...  Nie wiem, jak zrobić żeby zwracała tylko 1 wartość. Wtedy chyba nie byłaby w ogóle potrzebna.

2023-02-08 19:35 UTC, Y0ucandev requested changes

2023-02-08 19:35 UTC, Y0ucandev commented on tasks/src/main/java/org/example/aSerejaAndDima/ASerejaAndDima.java
> +    void loop() {
Metoda powinna być niżej. Pod memberami klasy. Memberzy powinni być private.,'

2023-02-08 19:35 UTC, Y0ucandev commented on tasks/src/main/java/org/example/aSerejaAndDima/ASerejaAndDima.java
> +    void whoseIsThisCard(short whoseTurnNow, short greaterNumber) {
Map<String,Integer> i problem z głowy '

2023-02-08 19:35 UTC, Y0ucandev commented on tasks/src/main/java/org/example/aSerejaAndDima/ASerejaAndDima.java
> +    void whoseIsThisCard(short whoseTurnNow, short greaterNumber) {
asdsadas

2023-02-12 16:35 UTC, merged